export enum TransactionType {
  FIAT_TO_CRYPTO = 'FIAT_TO_CRYPTO',
  FIAT_TO_FIAT = 'FIAT_TO_FIAT',
  CRYPTO_TO_FIAT = 'CRYPTO_TO_FIAT',
  CRYPTO_TO_CRYPTO = 'CRYPTO_TO_CRYPTO'
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  FLAGGED = 'FLAGGED',
  UNDER_REVIEW = 'UNDER_REVIEW'
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}

export enum ComplianceAction {
  DEPOSIT_PROCESSED = 'DEPOSIT_PROCESSED',
  WITHDRAWAL_PROCESSED = 'WITHDRAWAL_PROCESSED',
  VERIFICATION_REQUESTED = 'WITHDRAWAL_PROCESSED',
  TIER_UPGRADED = 'TIER_UPGRADED',
  ACCOUNT_FLAGGED = 'ACCOUNT_FLAGGED',
  SOURCE_OF_FUNDS_REQUESTED = 'SOURCE_OF_FUNDS_REQUESTED',
  SOURCE_OF_FUNDS_SUBMITTED = 'SOURCE_OF_FUNDS_SUBMITTED',
  AML_CHECK_PERFORMED = 'AML_CHECK_PERFORMED'
}